In [45]:
import numpy as np
np.random.seed(1)
arr=np.random.randint(10,size=(2,5))
print(arr)

print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.itemsize)
print(arr.nbytes)
print (arr[1,2])
print(arr[1:2,:3])
print(arr[:2,:3])
print(arr[0,:]

[[5 8 9 5 0]
 [0 1 7 6 9]]
2
(2, 5)
10
4
40
7
[[0 1 7]]
[[5 8 9]
 [0 1 7]]
[5 8 9 5 0]


In [47]:
np.random.seed(1)
arr=np.random.randint(10,size=10)
print(arr)
print(arr[3])
print(arr[-2])
print(arr[0:5:2])
print(arr[2:9:3])
print(arr[::-1])
arr[2]=10
print(arr)

[5 8 9 5 0 0 1 7 6 9]
5
6
[5 9 0]
[9 0 6]
[9 6 7 1 0 0 5 9 8 5]
[ 5  8 10  5  0  0  1  7  6  9]
