In [4]:
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr)
print(type(arr))

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [6]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [9]:
import numpy as np
arr=np.zeros(6)
print(arr)

[0. 0. 0. 0. 0. 0.]


In [12]:
import numpy as np
arr=np.ones((3,2),dtype=int)
print(arr)

[[1 1]
 [1 1]
 [1 1]]


In [16]:
import numpy as np
arr=np.array([2,3,4],dtype=float)
print(arr,type(arr))

[2. 3. 4.] <class 'numpy.ndarray'>


In [17]:
import numpy as np
arr=np.empty((2,2))
print(arr)

[[2.12199579e-314 4.67296746e-307]
 [5.69163624e-321 9.06092203e-312]]


In [19]:
import numpy as np
x=np.arange(0,20,2)
print(x)

[ 0  2  4  6  8 10 12 14 16 18]


In [21]:
import numpy as np
arr=np.linspace(0,1,6)
print(arr)

[0.  0.2 0.4 0.6 0.8 1. ]


In [22]:
np.random.random((3,3))

array([[0.13439056, 0.59403271, 0.98526607],
       [0.25478093, 0.59749509, 0.77027008],
       [0.05261951, 0.8548981 , 0.2001945 ]])