In [57]:
# 1
import numpy as np
arr=np.arange(1,21)
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
1
(20,)
20
int64


In [60]:
# 2
import numpy as np
np.random.seed(0)
arr=np.random.randint(50,size=(4,5))
print(arr)
print(arr.itemsize)
print(arr.nbytes)


[[44 47  0  3  3]
 [39  9 19 21 36]
 [23  6 24 24 12]
 [ 1 38 39 23 46]]
4
80


In [61]:
# 3
import numpy as np
arr=np.arange(1,13).reshape(3,4)
print(arr)
print(arr[2,3])
print(arr[-1:,:])
print(arr[:,-1:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
12
[[ 9 10 11 12]]
[[ 4]
 [ 8]
 [12]]


In [63]:
# 4
import numpy as np
np.random.seed(1)
arr=np.random.randint(10,size=(3,4))
print(arr)
print(arr[:2,:2])
print(arr[:,::2])
print(arr[:,::-1])

[[5 8 9 5]
 [0 0 1 7]
 [6 9 2 4]]
[[5 8]
 [0 0]]
[[5 9]
 [0 1]
 [6 2]]
[[5 9 8 5]
 [7 1 0 0]
 [4 2 9 6]]


In [62]:
# 5
import numpy as np
arr=np.arange(1,21).reshape(4,5) # larger array
view=arr[:3,:4] # view-changes affect the original array
view[0,0]=100 
print(arr)
copy_arr=arr[:3,:4].copy() # copy array-changes do not affect the original array
copy_arr[0,0]=200
print(arr) 
print(copy_arr) 

[[100   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]
 [ 16  17  18  19  20]]
[[100   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]
 [ 16  17  18  19  20]]
[[200   2   3   4]
 [  6   7   8   9]
 [ 11  12  13  14]]


In [42]:
# 6
import numpy as np
x=np.arange(1,13)
print(x)
matrix=x.reshape(3,4) # 3*4 matrix
print(matrix)
column1=x.reshape((12,1)) # reshape column vector using reshpe(12,1)
print(column1)
column2=x[:,np.newaxis] # reshape using x[:,np.newaxis]
print(column2)
print(np.array_equal(column1,column2)) # check both  results are identical

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]
True


In [51]:
# 7
import numpy as np
arr1=np.random.randint(1,10,size=(2,3))
arr2=np.random.randint(1,10,size=(2,3))
print(arr1)
print(arr2)
vertical1=np.vstack((arr1,arr2)) # join arrays vertically(row-wise)
vertical2=np.concatenate((arr1,arr2),axis=0) # also join row-wise
print(vertical1)
print(vertical2)
print(np.array_equal (vertical1,vertical2)) # check both results are identical
horizontal1=np.hstack((arr1,arr2)) # join arrays horizontally(column wise)
horizontal2=np.concatenate((arr1,arr2),axis=1) # also join column-wise
print(horizontal1)
print(horizontal2)
print(np.array_equal (horizontal1,horizontal2)) # check both results are identical


[[1 3 8]
 [8 8 4]]
[[1 9 8]
 [8 2 2]]
[[1 3 8]
 [8 8 4]
 [1 9 8]
 [8 2 2]]
[[1 3 8]
 [8 8 4]
 [1 9 8]
 [8 2 2]]
True
[[1 3 8 1 9 8]
 [8 8 4 8 2 2]]
[[1 3 8 1 9 8]
 [8 8 4 8 2 2]]
True


In [53]:
# 8
import numpy as np
arr=np.arange(1,16)
print(arr)
x=np.split(arr,3) # split arrays into 3 parts
x1=print(x[0])
x2=print(x[1])
x3=print(x[2])




[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [56]:
# 9
import numpy as np
arr=np.arange(1,25).reshape(6,4)
print(arr)
h=np.hsplit(arr,2)
h1=print(h[0])
h2=print(h[1])
v=np.vsplit(arr,2)
v1=print(v[0])
v2=print(v[1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]
 [17 18]
 [21 22]]
[[ 3  4]
 [ 7  8]
 [11 12]
 [15 16]
 [19 20]
 [23 24]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
